name: Update Firebase Config

on:
  push:
    branches:
      - gh-pages

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages üõéÔ∏è
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: List files üìÅ
        run: |
          echo "Repository structure:"
          ls -R

      - name: Inject Firebase config üîß
        run: |
          sed -i 's|__FIREBASE_API_KEY__|'${{ secrets.FIREBASE_API_KEY }}'|g' *.js
          sed -i 's|__FIREBASE_AUTH_DOMAIN__|'${{ secrets.FIREBASE_AUTH_DOMAIN }}'|g' *.js
          sed -i 's|__FIREBASE_PROJECT_ID__|'${{ secrets.FIREBASE_PROJECT_ID }}'|g' *.js
          sed -i 's|__FIREBASE_STORAGE_BUCKET__|'${{ secrets.FIREBASE_STORAGE_BUCKET }}'|g' *.js
          sed -i 's|__FIREBASE_MESSAGING_SENDER_ID__|'${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'|g' *.js
          sed -i 's|__FIREBASE_APP_ID__|'${{ secrets.FIREBASE_APP_ID }}'|g' *.js
